version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Setup Dependencies
          command: npm install
      - run:
          name: Linting
          command: yarn lint
      - run:
          name: Unit Testing
          command: CI=true yarn test:ci
      - run:
          name: E2E Testing
          command: yarn test:e2e
